export default {
  HEADER_1: "MIXD",
  HEADER_2: "WORLD CLASS WEB DESIGN",
  BANNER_CONTENT_1: "BEAUTIFUL FORM,",
  BANNER_CONTENT_2: "PERFECT FUNCTION.",
  BANNER_LINK: "See how we work",
  CLICK_HERE_LABEL: "Now click here!",
  SPOON_LABEL: "Nice Spoon",
};
